= Working with multiple browsers

Some web tests need to exercise two different browsers simultaneously. Workflow applications are a good example of this scenario: imagine for example a scenario where one user (say, a salesperson) raises an expense and another user (his or her manager) needs to approve this expense in a different session.

== Do you need to use multiple browsers?

Before you go down this path, there are often ways to avoid the use of two browsers in such scenarios. For example, suppose you need to automate the following scenario:

[source,gherkin]
----
Scenario: Expenses over $1000 need to be reviewed by a manager
Joe and Jane a sales people and Mark is their manager

Given Joe has raised an expenses claim for $1200
And Jane has raised an expenses claim for $900
When he submits his claim for processing
Then Mark should see the following expense claims in his inbox:
| Employee | Claim |
| Joe      | $1200 |
----

In this scenario, three actors are involved: Joe, Jane and Mark. You could test this using three browsers, one for each user. Or, knowing that the expense claim UI is tested elsewhere, you could invoke a web service to inject the claims directly into the system, and use a single web test for Mark, when he views his inbox. _Or_ you could dispense with web testing entirely, and use another web service to query Mark's inbox. There are often many ways to test a scenario.

== When you really do need to use multiple browsers

Nevertheless, there are cases where you really do need multiple browsers in the same test. Suppose you have the following (rather silly) test case:

[source,gherkin]
----
Scenario: Users are stubborn about their browser choice
    Given Joe likes firefox
    And Jane prefers chrome
    When Joe looks for foxes
    And Jane looks for fenders
    Then Joe should see mammals
    And Jane should see shiny stuff
----

The interesting thing here is that we have two actors, each using a different browser. How could you implement this test in Serenity?

=== Using Screenplay
Multiple browsers are easy to manage in Screenplay. In this case, you could just declare two browsers, and assign each of them to a different user, like this:

[source,java]
----
public class StepDefinitions {

    @Managed(driver = "firefox")
    WebDriver firefox;

    @Managed(driver = "chrome")
    WebDriver chrome;

    Actor joe = Actor.named("Joe");
    Actor jane = Actor.named("Jane");

    @Given("^Joe (?:likes|prefers) firefox$")
    public void joeLikesFirefox() throws Throwable {
        joe.can(BrowseTheWeb.with(firefox));
    }

    @And("^Jane (?:likes|prefers) chrome$")
    public void janeLikeChrome() throws Throwable {
        jane.can(BrowseTheWeb.with(chrome));
    }
	...
----

Then Joe and Jane will use Firefox and Chrome respectively for their subsequent web interactions.

One nice thing about this approach is that, once the driver is assigned to an actor, any UI interaction will use that driver, no matter what order the calls are made. So the following code will use Chrome or Firefox, depending on whether the actor in question is Jane or Joe:

[source,java]
----
	actor.attemptsTo(Open.url("https://www.google.co.uk"));
	actor.attemptsTo(
			Enter.theValue(search).into(By.name("q"))
			 	 .thenHit(Keys.ENTER)
);
----

=== Using @Managed drivers

The @Managed field can be used to declare drivers of specific types, in both JUnit tests and Cucumber step definitions. The driver you declare in this annotation will override any drivers declared in the `serenity.properties` file, and you can use the `option` attribute to pass in Chrome options, as shown here:

[source,java]
----
@Managed(driver = "chrome", options = "--headless")
WebDriver chrome;
----

=== Obtaining drivers dynamically

Sometimes you need a solution more dynamic than defining the drivers ahead of time with the `@Managed` annotation. In this case, you can use the Serenity `ThucydidesWebDriverSupport` class to allocate a dynamically driver by name.

For example, suppose you have the following Gherkin statement, where the browser name may vary:

[source,gherkin]
----
Given Joe likes to browse with firefox
----

Probably the best way to make both the actor (Joe) and the browser (firefox) dynamic is to use the `OnlineCast` class. The `OnlineCast` class represents the cast of actors we can call on to perform our web-based tests.

In practice, we can do this by creating an `OnlineCast` object and use it to create actors who can browse the web with a browser of a specified type. You can see an example of this in the following listing:

[source,java]
----
OnlineCast theCast = new OnlineCast(); 	(1)

@Before
public void setTheStage() {
	OnStage.setTheStage(theCast);		(2)
}

@Given("^(.*) likes to browse with (.*)")
public void joeBrowsesTheWebWith(String actorName, String driverType) throws Throwable {
	Actor actor = theCast.actorUsingBrowser(driverType).named(actorName);	(3)

	actor.attemptsTo(Open.url("https://www.google.co.uk"));
}
----
(1) Create a new cast
(2) Set the cast so that we can refer to actors later on using `theActorCalled()` and `theActorInTheSpotlight()`
(3) Retrieve an actor using a given browser with a given name

== Obtaining drivers from the WebDriverManager

Another alternative is to retrieve the `WebDriver` instance from the Serenity `WebDriverManager` class. This class keeps track of all the open drivers, and you can retrieve a driver either by it's type (e.g. "firefox"), or in conjunction with a unique name. If you provide the unique name, you can have several browsers of the same type simultaneously in the same test.

For example, the following code retrieves a Firefox instance associated with "joe":

[source,java]
----
WebDriver driver = ThucydidesWebDriverSupport.getWebdriverManager()
                                             .getWebdriverByName("joe", "firefox");
----

This method can be called from anywhere in the test suite.

== Using multiple browsers with Screenplay and legacy Page Object classes

Sometimes you need to use multiple browsers with test code that uses non-Screenplay page objects. You can do this quite easily, by extracting the WebDriver from the actor. For example, suppose you have a page that opens the Google home page:

[source,java]
----
@DefaultUrl("https://www.google.co.uk")
public static class GooglePage extends PageObject {
	public GooglePage(WebDriver driver) {
		super(driver);
	}
	...
}
----

A simple way to access this class is to wrap it in a `Task` class, like the one shown below:

[source,java]
----
public static class OpenGoogle implements Task {
	@Override
	public <T extends Actor> void performAs(T actor) {
		GooglePage page = new GooglePage(BrowseTheWeb.as(actor).getDriver());
		page.open();
	}

	public static OpenGoogle homePage() {
		return instrumented(OpenGoogle.class);
	}
}
----

A Screenplay actor can then open this page, with the corresponding driver instance, like this:

[source,java]
----
actor.attemptsTo(OpenGoogle.homePage());
----

=== Using the @Managed annotation for Remote drivers

Selenium Grid, as well as services like BrowserLabs and SauceSafe, offer a convenient way to scale your web tests by running them on batteries of remote machines. In Serenity, you can run your tests on a remote server simply by specifying the `webdriver.remote.url` property in your `serenity.properties` file or on the command line:

----
webdriver.remote.url=http://localhost:4444/wd/hub
----

You can also use the `saucelabs.url` or `browserstack.url` properties to work with one of these services.

As soon as you set a remote url, Serenity will use a Remote driver. However Serenity will still respect your choice of browsers on the remote server. For example, suppose you run a test with the following @Managed driver:

[source,java]
----
@Managed(driver = "chrome", options = "--headless")
WebDriver driver;
----

If you use a remote url, a Chrome driver will be used on the remote server.
